#!/bin/bash -xe
IMG_DIFF_TOOL=$STORAGE_PATH/tools/img_diff/img_diff

./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024

# Run cpu examples to get reference images
./bin/vklExamplesCPU -renderer density_pathtracer -batch -printStats -spp 50 -framebufferSize 1024 1024
./bin/vklExamplesCPU -renderer ray_march_iterator -batch -printStats -spp 2 -framebufferSize 1024 1024
./bin/vklExamplesCPU -renderer hit_iterator_renderer -batch -printStats -spp 2 -framebufferSize 1024 1024
./bin/vklExamplesCPU -renderer interval_iterator_debug -batch -printStats -spp 2 -framebufferSize 1024 1024

# Compare images generated by GPU examples vs CPU examples
$IMG_DIFF_TOOL density_pathtracer.pfm density_pathtracer_gpu.pfm
$IMG_DIFF_TOOL ray_march_iterator.pfm ray_march_iterator_gpu.pfm
$IMG_DIFF_TOOL hit_iterator_renderer.pfm hit_iterator_renderer_gpu.pfm
$IMG_DIFF_TOOL interval_iterator_debug.pfm interval_iterator_debug_gpu.pfm