#!/bin/bash -xe
## Copyright 2023 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

IMG_DIFF_TOOL=$STORAGE_PATH/tools/img_diff/img_diff

# Run tests over these volume types
VOLUME_TYPES="structuredRegular unstructured"

COMMON_ARGS="-batch -printStats -framebufferSize 1024 1024"

for volumeType in $VOLUME_TYPES; do

    ./bin/vklExamplesGPU -renderer density_pathtracer_gpu $COMMON_ARGS -volumeType $volumeType -spp 50 
    ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu $COMMON_ARGS -volumeType $volumeType -spp 2 
    ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu $COMMON_ARGS -volumeType $volumeType -spp 2 

    # Unstructured volumes do not yet support hit iterators on GPU
    if [ "$volumeType" != "unstructured" ]; then
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu $COMMON_ARGS -volumeType $volumeType -spp 2 
    fi

    # Run cpu examples to get reference images
    ./bin/vklExamplesCPU -renderer density_pathtracer $COMMON_ARGS -volumeType $volumeType -spp 50 
    ./bin/vklExamplesCPU -renderer ray_march_iterator $COMMON_ARGS -volumeType $volumeType -spp 2 
    ./bin/vklExamplesCPU -renderer interval_iterator_debug $COMMON_ARGS -volumeType $volumeType -spp 2 

    if [ "$volumeType" != "unstructured" ]; then
        ./bin/vklExamplesCPU -renderer hit_iterator_renderer $COMMON_ARGS -volumeType $volumeType -spp 2 
    fi

    # Compare images generated by GPU examples vs CPU examples
    $IMG_DIFF_TOOL density_pathtracer.pfm density_pathtracer_gpu.pfm
    $IMG_DIFF_TOOL ray_march_iterator.pfm ray_march_iterator_gpu.pfm
    $IMG_DIFF_TOOL interval_iterator_debug.pfm interval_iterator_debug_gpu.pfm

    if [ "$volumeType" != "unstructured" ]; then
        $IMG_DIFF_TOOL hit_iterator_renderer.pfm hit_iterator_renderer_gpu.pfm
    fi

    # Retain images in volume-specific subdirectory
    mkdir -p $volumeType
    mv *.pfm $volumeType/
done
