## Copyright 2020 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

set(COMPONENT_NAME c-blosc)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})
if (INSTALL_IN_SEPARATE_DIRECTORIES)
  set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE}/${COMPONENT_NAME})
endif()

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  URL ${BLOSC_URL}
  URL_HASH SHA256=${BLOSC_HASH}
  # c-blosc's -Wall blows up the log; -w via env to keep CMake's defaults
  CMAKE_COMMAND ${CMAKE_COMMAND} -E env
    "CXXFLAGS=$ENV{CXXFLAGS} -w" "CFLAGS=$ENV{CFLAGS} -w" ${CMAKE_COMMAND}
  CMAKE_ARGS
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} # c-blosc is a C project
    -DCMAKE_INSTALL_PREFIX:PATH=${COMPONENT_PATH}
    -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
    -DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
    -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
    -DCMAKE_BUILD_TYPE=${DEPENDENCIES_BUILD_TYPE}
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 # WA for CMake 4
    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
    -DBLOSC_IS_SUBPROJECT=ON
    -DBLOSC_INSTALL=ON
    -DPREFER_EXTERNAL_ZLIB=ON
    # c-blosc's old CMake policies would ignore ZLIB_ROOT
    -DCMAKE_POLICY_DEFAULT_CMP0074=NEW
    -DZLIB_ROOT=${ZLIB_PATH}
    -DBUILD_STATIC=OFF
  BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  BUILD_ALWAYS OFF
)

set(BLOSC_PATH ${COMPONENT_PATH})

ExternalProject_Add_StepDependencies(c-blosc
  configure
    zlib
)

