## Copyright 2020 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

set(COMPONENT_NAME boost)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})
if (INSTALL_IN_SEPARATE_DIRECTORIES)
  set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE}/${COMPONENT_NAME})
endif()

# OpenVDB needs those two (and their dependencies are pulled in automatically)
set(BOOST_LIBRARIES iostreams|interprocess)

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  URL ${BOOST_URL}
  URL_HASH SHA256=${BOOST_HASH}
  LIST_SEPARATOR |
  CMAKE_ARGS
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} # dependency Boost.Container is C
    -DCMAKE_INSTALL_PREFIX=${COMPONENT_PATH}
    -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
    -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
    -DCMAKE_BUILD_TYPE=${DEPENDENCIES_BUILD_TYPE}
    -DBUILD_SHARED_LIBS=ON
    -DBUILD_TESTING=OFF
    -DBOOST_INCLUDE_LIBRARIES=${BOOST_LIBRARIES}
    -DBOOST_INSTALL_LAYOUT=system
    # OpenVDB uses none of the compressors
    -DBOOST_IOSTREAMS_ENABLE_ZLIB=OFF
    -DBOOST_IOSTREAMS_ENABLE_BZIP2=OFF
    -DBOOST_IOSTREAMS_ENABLE_LZMA=OFF
    -DBOOST_IOSTREAMS_ENABLE_ZSTD=OFF
    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
  BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install --config ${DEPENDENCIES_BUILD_TYPE}
  BUILD_ALWAYS OFF
)

set(BOOST_PATH ${COMPONENT_PATH})
