// Copyright 2020 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

#pragma once

// Maximum iterator size over all supported volume and driver
// types, and for each target SIMD width.
#define VKL_MAX_INTERVAL_ITERATOR_SIZE_4 1503
#define VKL_MAX_INTERVAL_ITERATOR_SIZE_8 3007
#define VKL_MAX_INTERVAL_ITERATOR_SIZE_16 6015

#if defined(TARGET_WIDTH) && (TARGET_WIDTH == 4)
  #define VKL_MAX_INTERVAL_ITERATOR_SIZE VKL_MAX_INTERVAL_ITERATOR_SIZE_4
#elif defined(TARGET_WIDTH) && (TARGET_WIDTH == 8)
  #define VKL_MAX_INTERVAL_ITERATOR_SIZE VKL_MAX_INTERVAL_ITERATOR_SIZE_8
#else
  #define VKL_MAX_INTERVAL_ITERATOR_SIZE VKL_MAX_INTERVAL_ITERATOR_SIZE_16
#endif
#define VKL_MAX_HIT_ITERATOR_SIZE_4 383
#define VKL_MAX_HIT_ITERATOR_SIZE_8 767
#define VKL_MAX_HIT_ITERATOR_SIZE_16 1535

#if defined(TARGET_WIDTH) && (TARGET_WIDTH == 4)
  #define VKL_MAX_HIT_ITERATOR_SIZE VKL_MAX_HIT_ITERATOR_SIZE_4
#elif defined(TARGET_WIDTH) && (TARGET_WIDTH == 8)
  #define VKL_MAX_HIT_ITERATOR_SIZE VKL_MAX_HIT_ITERATOR_SIZE_8
#else
  #define VKL_MAX_HIT_ITERATOR_SIZE VKL_MAX_HIT_ITERATOR_SIZE_16
#endif
