## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI GPU Linux Workflow
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download-dpcpp-gfx:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/get_dpcpp_gfx_linux.yml@main
    with:
      dpcpp-version: sycl-nightly/20221001
      gfx-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12317/artifacts/Linux/Ubuntu/22.04/Release

  build-gpu-ubuntu22_04:
    secrets: inherit
    needs: download-dpcpp-gfx
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      artifact-out: build-gpu-ubuntu22_04
      artifact-path: ./build/install ./build/openvkl/build
      gfx-path: ${{ needs.download-dpcpp-gfx.outputs.gfx-path }}
      dpcpp-path: ${{ needs.download-dpcpp-gfx.outputs.dpcpp-path }}
      cmd: |
        export CC=clang
        export CXX=clang++
        gitlab/build.sh -D BUILD_OPENVDB=OFF -D BUILD_ISPCRT_GPU=ON \
                        -D OPENVKL_EXTRA_OPTIONS="-DOPENVKL_ENABLE_DEVICE_GPU=ON"

  test-build-from-install-ubuntu22_04-dg2:
    needs: [ download-dpcpp-gfx, build-gpu-ubuntu22_04 ]
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      gfx-path: ${{ needs.download-dpcpp-gfx.outputs.gfx-path }}
      dpcpp-path: ${{ needs.download-dpcpp-gfx.outputs.dpcpp-path }}
      options: --device=/dev/dri:/dev/dri
      cmd: |
        export CC=clang
        export CXX=clang++
        export LD_LIBRARY_PATH=`pwd`/build/install/lib:$LD_LIBRARY_PATH
        export PATH=`pwd`/build/install/bin:`pwd`/build/install:$PATH
        gitlab/build-from-install.sh

  test-pvc-ubuntu22_04:
    secrets: inherit
    needs: [ download-dpcpp-gfx, build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "pvc" ]'
      artifact-in: build-gpu-ubuntu22_04
      gfx-path: ${{ needs.download-dpcpp-gfx.outputs.gfx-path }}
      dpcpp-path: ${{ needs.download-dpcpp-gfx.outputs.dpcpp-path }}
      options: --device=/dev/dri:/dev/dri
      cmd: |
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU

  test-dg2-ubuntu22_04:
    secrets: inherit
    needs: [ download-dpcpp-gfx, build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      gfx-path: ${{ needs.download-dpcpp-gfx.outputs.gfx-path }}
      dpcpp-path: ${{ needs.download-dpcpp-gfx.outputs.dpcpp-path }}
      options: --device=/dev/dri:/dev/dri
      cmd: |
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
