## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI GPU Linux Workflow
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-gpu-ubuntu22_04:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      artifact-out: build-gpu-ubuntu22_04
      artifact-path: ./build/install ./build/openvkl/build
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      cmd: |
        export CC=clang
        export CXX=clang++
        gitlab/build.sh -D BUILD_OPENVDB=OFF -D BUILD_ISPCRT_GPU=ON \
                        -D OPENVKL_EXTRA_OPTIONS="-DOPENVKL_ENABLE_DEVICE_GPU=ON \
                           -DOPENVKL_DEVICE_CPU_STRUCTURED_REGULAR=OFF \
                           -DOPENVKL_DEVICE_CPU_STRUCTURED_REGULAR_LEGACY=ON"

  test-build-from-install-ubuntu22_04-dg2:
    needs: [ build-gpu-ubuntu22_04 ]
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        export CC=clang
        export CXX=clang++
        export LD_LIBRARY_PATH=`pwd`/build/install/lib:$LD_LIBRARY_PATH
        export PATH=`pwd`/build/install/bin:`pwd`/build/install:$PATH
        gitlab/build-from-install.sh

  test-pvc-ubuntu22_04:
    secrets: inherit
    needs: [ build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "pvc" ]'
      artifact-in: build-gpu-ubuntu22_04
      artifact-out: test-pvc-ubuntu22_04
      artifact-path: ./build/install/*.pfm
      artifact-on-failure: true
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
        ./bin/vklTestsGPU --durations yes
        ./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklBenchmarkGPU

        # Run cpu examples to get reference images
        ./bin/vklExamplesCPU -renderer density_pathtracer -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer ray_march_iterator -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer hit_iterator_renderer -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer interval_iterator_debug -batch -printStats -spp 2 -framebufferSize 1024 1024

        # Compare images generated by GPU examples vs CPU examples
        IMG_DIFF_TOOL=$STORAGE_PATH/tools/img_diff/img_diff
        $IMG_DIFF_TOOL density_pathtracer.pfm density_pathtracer_gpu.pfm
        $IMG_DIFF_TOOL ray_march_iterator.pfm ray_march_iterator_gpu.pfm
        $IMG_DIFF_TOOL hit_iterator_renderer.pfm hit_iterator_renderer_gpu.pfm
        $IMG_DIFF_TOOL interval_iterator_debug.pfm interval_iterator_debug_gpu.pfm

  test-dg2-ubuntu22_04:
    secrets: inherit
    needs: [ build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      artifact-out: test-dg2-ubuntu22_04
      artifact-path: ./build/install/*.pfm
      artifact-on-failure: true
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
        ./bin/vklTestsGPU --durations yes
        ./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklBenchmarkGPU

        # Run cpu examples to get reference images
        ./bin/vklExamplesCPU -renderer density_pathtracer -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer ray_march_iterator -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer hit_iterator_renderer -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer interval_iterator_debug -batch -printStats -spp 2 -framebufferSize 1024 1024

        # Compare images generated by GPU examples vs CPU examples
        IMG_DIFF_TOOL=$STORAGE_PATH/tools/img_diff/img_diff
        $IMG_DIFF_TOOL density_pathtracer.pfm density_pathtracer_gpu.pfm
        $IMG_DIFF_TOOL ray_march_iterator.pfm ray_march_iterator_gpu.pfm
        $IMG_DIFF_TOOL hit_iterator_renderer.pfm hit_iterator_renderer_gpu.pfm
        $IMG_DIFF_TOOL interval_iterator_debug.pfm interval_iterator_debug_gpu.pfm

  test-pvc-ubuntu22_04-ispcrt-mem-pool:
    secrets: inherit
    needs: [ build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "pvc" ]'
      artifact-in: build-gpu-ubuntu22_04
      artifact-out: test-pvc-ubuntu22_04
      artifact-path: ./build/install/*.pfm
      artifact-on-failure: true
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        export ISPCRT_MEM_POOL=1
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
        ./bin/vklTestsGPU --durations yes
        ./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklBenchmarkGPU

        # Run cpu examples to get reference images
        ./bin/vklExamplesCPU -renderer density_pathtracer -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer ray_march_iterator -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer hit_iterator_renderer -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer interval_iterator_debug -batch -printStats -spp 2 -framebufferSize 1024 1024

        # Compare images generated by GPU examples vs CPU examples
        IMG_DIFF_TOOL=$STORAGE_PATH/tools/img_diff/img_diff
        $IMG_DIFF_TOOL density_pathtracer.pfm density_pathtracer_gpu.pfm
        $IMG_DIFF_TOOL ray_march_iterator.pfm ray_march_iterator_gpu.pfm
        $IMG_DIFF_TOOL hit_iterator_renderer.pfm hit_iterator_renderer_gpu.pfm
        $IMG_DIFF_TOOL interval_iterator_debug.pfm interval_iterator_debug_gpu.pfm

  test-dg2-ubuntu22_04-ispcrt-mem-pool:
    secrets: inherit
    needs: [ build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      artifact-out: test-dg2-ubuntu22_04
      artifact-path: ./build/install/*.pfm
      artifact-on-failure: true
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        export ISPCRT_MEM_POOL=1
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
        ./bin/vklTestsGPU --durations yes
        ./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklBenchmarkGPU

        # Run cpu examples to get reference images
        ./bin/vklExamplesCPU -renderer density_pathtracer -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer ray_march_iterator -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer hit_iterator_renderer -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesCPU -renderer interval_iterator_debug -batch -printStats -spp 2 -framebufferSize 1024 1024

        # Compare images generated by GPU examples vs CPU examples
        IMG_DIFF_TOOL=$STORAGE_PATH/tools/img_diff/img_diff
        $IMG_DIFF_TOOL density_pathtracer.pfm density_pathtracer_gpu.pfm
        $IMG_DIFF_TOOL ray_march_iterator.pfm ray_march_iterator_gpu.pfm
        $IMG_DIFF_TOOL hit_iterator_renderer.pfm hit_iterator_renderer_gpu.pfm
        $IMG_DIFF_TOOL interval_iterator_debug.pfm interval_iterator_debug_gpu.pfm