## Copyright 2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

name: CI GPU Linux Workflow
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-gpu-ubuntu22_04:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      artifact-out: build-gpu-ubuntu22_04
      artifact-path: ./build/install ./build/openvkl/build
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      cmd: |
        export CC=clang
        export CXX=clang++
        gitlab/build.sh -D BUILD_OPENVDB=OFF -D BUILD_ISPCRT_GPU=ON \
                        -D OPENVKL_EXTRA_OPTIONS="-DOPENVKL_ENABLE_DEVICE_GPU=ON"

  test-build-from-install-ubuntu22_04-dg2:
    needs: [ build-gpu-ubuntu22_04 ]
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        export CC=clang
        export CXX=clang++
        export LD_LIBRARY_PATH=`pwd`/build/install/lib:$LD_LIBRARY_PATH
        export PATH=`pwd`/build/install/bin:`pwd`/build/install:$PATH
        gitlab/build-from-install.sh

  test-pvc-ubuntu22_04:
    secrets: inherit
    needs: [ build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "pvc" ]'
      artifact-in: build-gpu-ubuntu22_04
      artifact-out: test-pvc-ubuntu22_04
      artifact-path: ./build/install/*.pfm
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
        ./bin/vklTestsGPU --durations yes
        ./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklBenchmarkGPU

  test-dg2-ubuntu22_04:
    secrets: inherit
    needs: [ build-gpu-ubuntu22_04 ]
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker_gpu.yml@main
    with:
      submodules: true
      image: ubuntu:22.04
      runs-on: '[ "Linux", "docker", "dg2" ]'
      artifact-in: build-gpu-ubuntu22_04
      artifact-out: test-dg2-ubuntu22_04
      artifact-path: ./build/install/*.pfm
      dpcpp-version: sycl-nightly/20221214
      gfx-driver-version: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
      options: --device=/dev/dri:/dev/dri
      cmd: |
        cd ./build/install
        export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
        ./bin/vklTutorialGPU
        ./bin/vklTestsGPU --durations yes
        ./bin/vklExamplesGPU -renderer density_pathtracer_gpu -batch -printStats -spp 50 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer ray_march_iterator_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer hit_iterator_renderer_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklExamplesGPU -renderer interval_iterator_debug_gpu -batch -printStats -spp 2 -framebufferSize 1024 1024
        ./bin/vklBenchmarkGPU
